apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:

      - name: backend-user
        image: docker.io/machariavck/udagram-api-user
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: p3-secrets
              key: POSTGRES_USERNAME
        
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: p3-secrets
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env
              key: POSTGRES_DB
        
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env
              key: POSTGRES_HOST

        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env
              key: AWS_REGION
        
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env
              key: AWS_PROFILE
        
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env
              key: AWS_BUCKET
        
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env
              key: URL
        
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: p3-secrets
              key: JWT_SECRET
