apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: machariavck/udagram-api-user:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: env
          - secretRef:
              name: p3-secrets
