apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: machariavck/udagram-api-feed:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /root/.aws
            name: aws-volume
            readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: p3-secrets
          - configMapRef:
              name: env
      volumes:
        - name: aws-volume
          secret:
            secretName: aws
            items:
              - key: cfg
                path: config
              - key: creds
                path: credentials
                