version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:  
  build-images-and-publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run:
          name: "Running docker-compose to set up base images in the remote environment"
          command: docker-compose -f docker-compose-build.yml build
      - run:
          name: "Tagging the images.."
          command: |
            docker tag udagram-reverseproxy $DOCKER_LOGIN/udagram-reverseproxy
            docker tag udagram-api-user $DOCKER_LOGIN/udagram-api-user
            docker tag udagram-api-feed $DOCKER_LOGIN/udagram-api-feed
            docker tag udagram-frontend $DOCKER_LOGIN/udagram-frontend:v7
      - run:
          name: "Pushing the images to the registry.."
          command: |
            docker push $DOCKER_LOGIN/udagram-reverseproxy
            docker push $DOCKER_LOGIN/udagram-api-user
            docker push $DOCKER_LOGIN/udagram-api-feed
            docker push $DOCKER_LOGIN/udagram-frontend:v7
      - run:
          name: "its done"
          command: |
            echo "We're done"

workflows:
  publish-images:
    jobs:
      - build-images-and-publish